import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

interface userType {
  id: Number,
  name: String,
  age: Number
}

const Home: NextPage = () => {
  const [users, setUsers] = useState<userType[] | undefined>(undefined);
  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true)
    fetch('/api/users')
      .then((res) => res.json())
      .then((data) => {
        setUsers(data)
        setLoading(false)
        console.log(data)
      })
  }, [])
  if(isLoading) return <p>Loading...</p>

  return (
    <>
      <Head>
        <title>Workout Guru</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {users && users.map((user) => (
            <div>
              <p>{user.age.toString()}</p>
              <p>{user.name}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
